trigger:
  branches:
    include:
      - main  # Trigger pipeline on changes to the main branch

schedules:
  - cron: "55 15 * * *"  # Runs daily at 15:55 UTC
    displayName: Daily Test Execution
    branches:
      include:
        - main  # Schedule runs only for the main branch
    always: true  # Run even if there are no code changes

pr:
  branches:
    include:
      - main  # Trigger pipeline on pull requests to the main branch

jobs:
- job: RunTests
  displayName: Run Robot Framework Tests
  pool:
    vmImage: ubuntu-latest

  steps:
    # Checkout the repository
    - task: PowerShell@2
      displayName: Checkout code

    # Log Public IP Address
    - script: |
        curl https://ifconfig.me
      displayName: Log Public IP Address

    # Set up Python
    - task: UsePythonVersion@0
      displayName: Set up Python
      inputs:
        versionSpec: '3.x'
        addToPath: true

    # Install Python dependencies
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: Install Python dependencies

    # Initialize RF Browser (downloads browser binaries)
    - script: |
        rfbrowser init
      displayName: Initialize RF Browser

    # Install Playwright system dependencies
    - script: |
        playwright install-deps
      displayName: Install Playwright dependencies

    # Run the tests
    - script: |
        robot --outputdir results/ tests/
      displayName: Run Robot Framework tests

    # Publish Robot Framework test results
    - task: PublishPipelineArtifact@1
      displayName: Upload Robot Framework test results
      inputs:
        targetPath: results/
        artifactName: robot-results

    # Publish screenshots
    - task: PublishPipelineArtifact@1
      displayName: Upload screenshots
      inputs:
        targetPath: results/browser/screenshot/
        artifactName: screenshots
