name: Robot Daily Test Execution

on:
  schedule:
    - cron: '55 15 * * *'  # Runs daily at 15:55 UTC (adjust timezone as needed)
  workflow_dispatch:        # Allows manual triggering

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify exact version for reliability

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libgbm1 \
            libasound2 \
            libpangocairo-1.0-0

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install robotframework
          pip install robotframework-browser
          pip install playwright

      - name: Install Playwright browsers
        run: |
          playwright install chromium
          playwright install-deps  # Install browser system dependencies

      - name: Run tests
        run: |
          robot --outputdir results/ tests/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-results
          path: |
            results/output.xml
            results/log.html
            results/report.html