name: Robot Daily Test Execution

# Schedule the workflow to run daily at midnight (UTC)
on:
  schedule:
    - cron: '50 14 * * *' # Adjust the time as needed

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (if your tests require Python)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Replace with the required Python version

      # Install dependencies (if applicable)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run the tests
      - name: Run tests
        run: |
          robot tests/