name: Robot Daily Test Execution

on:
  schedule:
    - cron: '55 15 * * *'  # Runs daily at 15:55 UTC (adjust timezone as needed)
  workflow_dispatch:        # Allows manual triggering

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install robotframework
          pip install robotframework-browser
          pip install robotframework-requests
          pip install playwright

      # Initialize RF Browser (downloads browser binaries)
      - name: Initialize RF Browser
        run: |
          rfbrowser init

      - name: Install Playwright browsers
        run: |
          playwright install chromium
          playwright install-deps

      # Run tests
      - name: Run tests
        run: |
          robot --outputdir results/ tests/

      # Upload test results and screenshots
      - name: Upload test results and screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-results
          path: |
            results/output.xml
            results/log.html
            results/report.html
            results/*.png