name: Robot Daily Test Execution

on:
  schedule:
    - cron: '50 14 * * *' # Adjust the time as needed
  workflow_dispatch: # Allows manual triggering

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Initialize RF Browser (downloads browser binaries)
      - name: Initialize RF Browser
        run: |
          rfbrowser init

      # Run the tests
      - name: Run tests
        run: |
          robot tests/

      # Upload Robot Framework reports
      - name: Upload Robot Framework reports
        uses: actions/upload-artifact@v3
        with:
          name: robot-reports
          path: .  # Adjust the path to where your reports are generated