name: Robot Daily Test Execution

on:
  schedule:
    - cron: '55 15 * * *'  # Runs daily at 15:55 UTC
  workflow_dispatch:        # Allows manual triggering

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log Public IP Address
        run: |
          curl https://ifconfig.me

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Initialize RF Browser (downloads browser binaries)
      - name: Initialize RF Browser
        run: |
          rfbrowser init

      # Install Playwright system dependencies
      - name: Install Playwright dependencies
        run: |
          playwright install-deps

      # Run the tests
      - name: Run tests
        run: |
          robot --outputdir results/ tests/

      # Upload Robot Framework test results
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-results
          path: |
            results/output.xml
            results/log.html
            results/report.html

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: results/browser/screenshot/*.png