name: Robot Daily Test Execution

# Schedule the workflow to run daily at 14:50 UTC
on:
  schedule:
    - cron: '55 14 * * *' # Adjust the time as needed
  workflow_dispatch: # Add this to enable manual triggering

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Initialize RF Browser
        run: |
          rfbrowser init

      - name: Run tests
        run: |
          robot tests/ 